### ISSUE TITLE
Security Data Issues Secrets in clear text

### ISSUE THREAD

**Issue by shaybenb** [johnlui97/MarauderAPI#1]
Hi,<br><br>url : https://github.com/johnlui97/MarauderAPI/blob/5fcd5bb580e06010af90f30c5d3f899cf83c8439/app.js <br><br>You have commit that need to remove from the github history<br>attacker can see it and use it ...<br><br>encrypt your secrets !!!!<br><br>Our Bug Help you to be more Secure and protect your data ?<br>Buy me a coffee (or more likely a beer)<br>https://www.paypal.com/paypalme/bugbounty1/150USD<br>https://www.buymeacoffee.com/bugbounty<br>☕☕☕☕☕

**Comment by johnlui97** [comment]
ok should be removed now, thanks.

**Comment by shaybenb** [comment]
Our Bug Help you to be more Secure and protect your data ?
Buy me a coffee (or more likely a beer)
https://www.paypal.com/paypalme/bugbounty1/150USD
https://www.buymeacoffee.com/bugbounty
☕☕☕☕☕
